version: "3"

services: 
  org:
    image: orgproject:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: always
    links:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "sql123"
      ACCEPT_EULA: "Y"
    ports:
      - "5434:1433"